# Server Configuration
server.port=5002

# Spring Application Name
spring.application.name=api-gateway

# Gateway Discovery Configuration (The "Magic" Routing)
# Automatically creates routes based on service names registered in Eureka
spring.cloud.gateway.discovery.locator.enabled=true
# Converts service names to lowercase (e.g., PRODUCT-SERVICE -> /product-service)
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Eureka Client Configuration
# Tells the Gateway where to find the Eureka Server
eureka.client.service-url.defaultZone=http://localhost:5001/eureka/
